RestaurantLogBook.UI/Areas/Manager/Models/AllTasksViewModel.cs
using RestaurantLogBook.Data.Models;
using System.Collections.Generic;

namespace RestaurantLogBook.ASPClient.Areas.Manager.Models
{
    public class AllTasksViewModel
    {
        public string LogBookName { get; set; }
        public int LogBookId { get; set; }
        public ICollection<TaskViewModel> Tasks { get; set; }
        public ICollection<string> PossibleAssignees { get; set; }
        public ICollection<string> PossibleTags { get; set; }
    }
}

RestaurantLogBook.UI/Areas/Manager/Models/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantLogBook.ASPClient.Areas.Manager.Models
{
    public class FilterViewModel
    {
        public int LogBookId { get; set; }
        public string AuthorFilter { get; set; }
        public string DateFilter { get; set; }
        public bool IsDoneFilter { get; set; }
        public string AssigneeFilter { get; set; }
        public ICollection<string> TagsFilter { get; set; }

        //public ICollection<TaskViewModel> Tasks { get; set; }
    }
}

RestaurantLogBook.UI/Areas/Manager/Models/ManagerLogBookViewModel.cs
using System.Collections.Generic;

namespace RestaurantLogBook.ASPClient.Areas.Manager.Models
{
    public class ManagerLogBookViewModel
    {
        public int LogBookId { get; set; }
        public string LogBookName { get; set; }
        public ICollection<string> Tags { get; set; }
        public string Author { get; set; }
        public ICollection<string> PossibleAssignees { get; set; }
    }
}

RestaurantLogBook.UI/Areas/Manager/Controllers/ManagerLogBooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestaurantLogBook.ASPClient.Areas.Manager.Mappers.Contracts;
using RestaurantLogBook.ASPClient.Areas.Manager.Models;
using RestaurantLogBook.Data.Models;
using RestaurantLogBook.Services.Contracts;
using RestaurantLogBook.Services.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace RestaurantLogBook.ASPClient.Areas.Manager.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = "Manager")]
    public class ManagerLogBooksController : Controller
    {

        private readonly ILogBookService logBookService;
        private readonly IManagerViewModelMapper<ICollection<LogBook>, AllManagerLogBooksViewModel> logBooksMapper;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IManagerTaskService managerTaskService;
        private readonly IManagerViewModelMapper<ICollection<ManagerTask>, AllTasksViewModel> tasksMapper;

        public ManagerLogBooksController(ILogBookService logBookService, IManagerViewModelMapper<ICollection<LogBook>, AllManagerLogBooksViewModel> logBooksMapper, UserManager<ApplicationUser> userManager, IManagerTaskService managerTaskService, IManagerViewModelMapper<ICollection<ManagerTask>, AllTasksViewModel> tasksMapper)
        {
            this.logBookService = logBookService ?? throw new ArgumentNullException(nameof(logBookService));
            this.logBooksMapper = logBooksMapper ?? throw new ArgumentNullException(nameof(logBooksMapper));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            this.managerTaskService = managerTaskService ?? throw new ArgumentNullException(nameof(managerTaskService));
            this.tasksMapper = tasksMapper ?? throw new ArgumentNullException(nameof(tasksMapper));
        }

        public async Task<IActionResult> Index()
        {
            var userName = User.Identity.Name;
            var logbooks = await this.logBookService.GetAllLogBooksAsync(userName);
            var model = this.logBooksMapper.MapFrom(logbooks);
            return View(model);
        }

        public async Task<IActionResult> AddTask(int id)
        {
            var logBook = await this.logBookService.GetLogBookBy(id);
            var model = new CreateManagerTaskViewModel()
            {
                LogBookId = id,
                AllTags = logBook.LogBookTags.Select(t => t.Tag.Name).ToList(),
                Author = User.Identity.Name,
                LogBookName = logBook.Name
            };
            return PartialView("_AddTaskPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTask(CreateManagerTaskViewModel model)
        {
            var logBook = await this.logBookService.GetLogBookBy(model.LogBookId);
            if (!this.ModelState.IsValid)
            {
                model.AllTags = logBook.LogBookTags.Select(t => t.Tag.Name).ToList();
                model.Author = User.Identity.Name;
                model.LogBookName = logBook.Name;
                model.PossibleAssignees = logBook.LogBookManagers.Select(lbm => lbm.Manager.Name).ToList();
                return View(model);
            }
            try
            {
                await this.managerTaskService.AddManagerTaskAsync(model.Author, model.LogBookId, model.SelectedTags, model.Text, model.SelectedAssignee);
                return Json(new { message = "Successfully added task" });
            }
            catch (CustomException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return Json(new { message = ex.Message });
            }
        }

        public async Task<IActionResult> AllTasks(int id)
        {
            var logBook = await this.logBookService.GetLogBookBy(id);
            if (logBook.ManagerTasks.Count == 0)
            {
                return View(new AllTasksViewModel(){ LogBookId = logBook.LogBookId, LogBookName = logBook.Name, Tasks = null });
            }
            var model = this.tasksMapper.MapFrom(logBook.ManagerTasks);
            return View(model);
        }

        public async Task<IActionResult> ChangeTaskStatus(int id)
        {
            try
            {
                var task = await this.managerTaskService.ChangeTaskStatusAsync(id);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> FilterTasksStatus(FilterViewModel model)
        {
            try
            {
                //var task = await this.managerTaskService.Filter(model);
                return Ok();
            }
            catch
            {
                return Ok();
            }
        }

    }
}

RestaurantLogBook.UI/Areas/Manager/Views/ManagerLogBooks/AllTasks.cshtml
@model AllTasksViewModel
@{
    ViewData["Title"] = "AllTasks";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<div class="listing-detail-header mb50">
    <div class="container">
        @{
            if (Model.Tasks == null)
            {
                <h2 id="top" class="font300">No Tasks Yet</h2>
                <div class="modal-content">
                    @await Html.PartialAsync("_AddTaskPartial", new CreateManagerTaskViewModel() { LogBookId = Model.LogBookId, LogBookName = Model.LogBookName, PossibleAssignees = Model.PossibleAssignees, AllTags = Model.PossibleTags });
                </div>
            }
            else
            {
                <h2 id="top" class="font300">Tasks for @Model.LogBookName</h2>

                <div class="panel panel-white">
                    <div class="panel-body">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add Task</button>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    @await Html.PartialAsync("_AddTaskPartial", new CreateManagerTaskViewModel() { LogBookId = Model.LogBookId, LogBookName = Model.LogBookName, PossibleAssignees = Model.PossibleAssignees, AllTags = Model.PossibleTags });
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container filter">
                    @await Html.PartialAsync("_Filter", new FilterViewModel { LogBookId = Model.LogBookId });
                </div>
                <table id="tasks" class="display table table-responsive table-striped">
                    <thead>
                        <tr>
                            <th width="50%">Task</th>
                            <th width="10%">Author</th>
                            <th>Date</th>
                            <th width="8%">Assignee</th>
                            <th>Tags</th>
                            <th width="8%">Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Tasks)
                        {
                            <tr>
                                @await Html.PartialAsync("_TaskPartial", new TaskViewModel { TaskId = item.TaskId, Author = item.Author, Date = item.Date, IsDone = item.IsDone, Text = item.Text, Tags = item.Tags, Assignee = item.Assignee })
                            </tr>
                        }
                    </tbody>
                </table>
            }
        }
    </div>
</div>

@section scripts {
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="~/js/Manager-area/alltasks.js"></script>

    <script>
        $(".btn").on("click", function (ev) {
            var $element = $(this);
            if ($element.hasClass("btn-outline-secondary")) {
                $element.removeClass("btn-outline-secondary").addClass("btn btn-info");
                return;
            }
            if ($element.hasClass("btn-info")) {
                $element.removeClass("btn-info").addClass("btn-outline-secondary");
            }
        });
    </script>

}
@section css {
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
}

RestaurantLogBook.UI/Areas/Manager/Views/ManagerLogBooks/Index.cshtml
@model AllManagerLogBooksViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}


<div class="listing-detail-header mb50">
    <div class="container">
        <h2 id="top" class="font300">Your LogBooks</h2>
        <table id="example" class="display table">
            <thead>
                <tr>
                    <th width="50%">LogBook</th>
                    <th width="10%">Options</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.LogBooks)
                {
                    <tr>
                        <td><a asp-area="Manager" asp-controller="ManagerLogBooks" asp-action="AllTasks" asp-route-id="@item.LogBookId" style="font-size:20px">@item.LogBookName</a></td>
                        <td>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add Task</button>
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        @await Html.PartialAsync("_AddTaskPartial", new CreateManagerTaskViewModel() { LogBookId = item.LogBookId, LogBookName = item.LogBookName, PossibleAssignees = item.PossibleAssignees, AllTags = item.Tags });
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@section scripts {
    <script src="~/js/Manager-area/index.js"></script>

    <script>
        $(".btn").on("click", function (ev) {
            var $element = $(this);
            if ($element.hasClass("btn-outline-secondary")) {
                $element.removeClass("btn-outline-secondary").addClass("btn btn-info");
                return;
            }
            if ($element.hasClass("btn-info")) {
                $element.removeClass("btn-info").addClass("btn-outline-secondary");
            }
        });
    </script>

}

RestaurantLogBook.UI/Areas/Manager/Views/ManagerLogBooks/_AddTaskPartial.cshtml
@model CreateManagerTaskViewModel
@{
    ViewData["Title"] = "_AddTaskPartial";
    Layout = null;
}
<div id="addform">

    <form runat="server" asp-controller="Establishments" asp-action="Details" method="post" enctype="multipart/form-data">
        <div class="form-group modal-body">
            <label asp-for="@Model.Text">@Model.LogBookName New Task</label>
            <textarea rows="6" asp-for="@Model.Text" id="text" class="form-control" style="max-width:100%"></textarea>
            <span asp-validation-for="@Model.Text" class="text-danger"></span>
            <br />
            <select id="assignee">
                <option selected> -- select assignee -- </option>
                @foreach (var item in Model.PossibleAssignees)
                {
                    <option>@item</option>
                }
            </select>

            <select id="priority">
                <option selected> -- select priority -- </option>
                <option>High</option>
                <option>Medium</option>
                <option>Low</option>
            </select>


            @if (Model.AllTags.Count > 0)
            {
                <div id="select">
                    <br />
                    <div class="form-group">
                        <label>Tags: </label>
                        @foreach (var tag in Model.AllTags)
                        {
                            <button type="button" class="btn btn-outline-secondary">@tag</button>
                        }
                    </div>
                </div>
            }
            <button data-ajaxurl="/Manager/ManagerLogBooks/AddTask/" data-tags="@Model.SelectedTags" data-author="@Model.Author" data-id="@Model.LogBookId" type="submit" class="btn btn-success final">Add</button>
            <button style="float:right" type="button" class="btn btn-danger cancel">Cancel</button>
        </div>
    </form>
</div>
<span id="anti-forgery-span">@Html.AntiForgeryToken()</span>

<script src="~/js/Manager-area/addtask.js"></script>

<link href="~/css/admin-area/createestablishment.css" />

RestaurantLogBook.UI/Areas/Manager/Views/ManagerLogBooks/_Filter.cshtml
@model FilterViewModel
@{
    ViewData["Title"] = "_Filter";
    Layout = null;
}

<div class="container">
    <button type="button" class="btn btn-dark" data-toggle="collapse" data-target="#collapse">Filter</button>
    <br />
    <div id="collapse" class="collapse">
        <div class="col-md-2">
            <form>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="@Model.DateFilter"></label>
                    <input asp-for="@Model.DateFilter" id="name" class="form-control" />
                </div>
                <a data-ajaxurl="/Admin/Tags/Create/" data-name="@Model.AssigneeFilter" id="create" class="btn btn-primary">Create</a>
            </form>
            <br />
        </div>
    </div>
</div>

RestaurantLogBook.UI/Areas/Manager/Views/ManagerLogBooks/_TaskPartial.cshtml
@model TaskViewModel
@{
    ViewData["Title"] = "Task";
    Layout = null;
}

<td>@Model.Text</td>
<td>@Model.Author</td>
<td>@Model.Date</td>
<td>@Model.Assignee</td>
<td>@string.Join(" | ", @Model.Tags)</td>
@if (Model.IsDone == false)
{
    <td><a data-id="@Model.TaskId" class="btn btn-warning done">Not Done</a></td>
}
else
{
    <td><a data-id="@Model.TaskId" class="btn btn-success done">Done</a></td>
}